export const postsData = [
  {
    title: "Nuevo teclado mecánico RGB para setups productivos",
    content: "Presentamos un teclado mecánico cómodo, preciso y con iluminación RGB personalizable, pensado para trabajar, estudiar y jugar durante horas.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
    likes: 1840,
    shares: 96,
    impressions: 24500,
    comments: [
      "Me gusta mucho el diseño, se ve bastante premium para un teclado de este rango.",
      "Lo usaría para programar, pero me preocupa que las teclas hagan demasiado ruido.",
      "La iluminación RGB está genial, aunque ojalá el software fuera más fácil de configurar.",
      "¿Tiene distribución española con la ñ?",
      "Se ve perfecto para un setup minimalista.",
      "Me gusta que sirva tanto para trabajar como para jugar.",
      "El precio me parece correcto si la calidad de construcción es buena.",
      "Echo en falta que incluya reposamuñecas.",
      "Compré uno parecido y la diferencia al escribir fue enorme.",
      "Buena pinta, aunque me gustaría ver una review con sonido de las teclas.",
    ],
  },
  {
    title: "Auriculares inalámbricos con cancelación de ruido",
    content: "Nuestros auriculares inalámbricos ofrecen sonido claro, batería de larga duración y cancelación de ruido para concentrarte en cualquier lugar.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
    likes: 2630,
    shares: 142,
    impressions: 38200,
    comments: [
      "La cancelación de ruido es justo lo que necesito para estudiar en transporte público.",
      "Me interesa saber si son cómodos después de varias horas.",
      "El diseño es bonito, pero me gustaría que hubiera más colores.",
      "La batería parece bastante buena si realmente dura todo el día.",
      "He tenido auriculares baratos que se desconectaban mucho, espero que estos no.",
      "Perfectos para trabajar desde casa sin escuchar ruido de fondo.",
      "El precio me parece algo alto, aunque si el sonido es bueno puede merecer la pena.",
      "¿Incluyen estuche de carga?",
      "Me gusta que no sean demasiado grandes.",
      "Buena opción si el micrófono también funciona bien en llamadas.",
    ],
  },
  {
    title: "Smartwatch con batería de larga duración",
    content: "Un reloj inteligente diseñado para controlar tu actividad diaria, recibir notificaciones y medir tu progreso deportivo sin cargarlo cada noche.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
    likes: 3210,
    shares: 188,
    impressions: 51600,
    comments: [
      "Me interesa sobre todo por la batería, odio cargar el reloj todos los días.",
      "El diseño se ve elegante y no tan deportivo como otros modelos.",
      "¿Se puede conectar con iPhone?",
      "Las funciones de deporte me parecen útiles, pero quiero saber si mide bien el sueño.",
      "Buen producto para gente que entrena varias veces por semana.",
      "Me gustaría que tuviera pagos contactless.",
      "La pantalla parece grande y clara.",
      "Si la batería dura varios días, puede ser muy buena compra.",
      "No soy fan de los smartwatches enormes, este parece tener buen tamaño.",
      "El precio será clave para decidir si merece la pena.",
    ],
  },
  {
    title: "Mochila tecnológica para portátil y accesorios",
    content: "Una mochila resistente, cómoda y con compartimentos organizados para llevar portátil, cargadores, tablet y accesorios de forma segura.",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
    likes: 970,
    shares: 61,
    impressions: 13900,
    comments: [
      "Me vendría genial para ir a clase con el portátil y el cargador.",
      "Tiene buena pinta, pero habría que ver si protege bien en días de lluvia.",
      "Me gusta que tenga varios compartimentos, odio llevar todo mezclado.",
      "El diseño es sobrio y profesional.",
      "¿Cabe un portátil de 16 pulgadas?",
      "Parece cómoda para llevarla todo el día.",
      "Me gustaría que tuviera bolsillo antirrobo.",
      "Buena opción para estudiantes y gente que trabaja fuera.",
      "Si el material es resistente, puede durar bastante.",
      "La compraría si no es demasiado grande.",
    ],
  },
  {
    title: "Lámpara LED de escritorio con intensidad ajustable",
    content: "Mejora tu zona de trabajo con una lámpara LED moderna, regulable y pensada para reducir la fatiga visual durante largas sesiones.",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c",
    likes: 1280,
    shares: 74,
    impressions: 19800,
    comments: [
      "Esto me vendría perfecto para estudiar por la noche.",
      "Me gusta que se pueda regular la intensidad.",
      "El diseño combina muy bien con setups minimalistas.",
      "¿Tiene luz cálida y fría?",
      "La fatiga visual es un problema real cuando pasas horas frente al ordenador.",
      "Parece sencilla pero útil.",
      "Me gustaría saber si ocupa mucho espacio en la mesa.",
      "Buena compra para oficinas pequeñas.",
      "Si consume poco, mejor todavía.",
      "La veo ideal para un escritorio de programación.",
    ],
  },
  {
    title: "Ratón ergonómico para largas jornadas",
    content: "Un ratón cómodo y preciso creado para reducir molestias en la muñeca durante horas de trabajo, estudio o edición.",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46",
    likes: 1560,
    shares: 83,
    impressions: 22100,
    comments: [
      "Trabajo muchas horas con el ordenador y esto me interesa bastante.",
      "He probado ratones ergonómicos y al principio cuesta acostumbrarse.",
      "Me gustaría saber si sirve bien para gaming casual.",
      "El diseño parece cómodo, aunque un poco grande.",
      "La muñeca se nota mucho después de usar un ratón normal todo el día.",
      "¿Es inalámbrico o con cable?",
      "Buena opción para oficina.",
      "Si tiene buena precisión, puede ser muy útil para diseño.",
      "Me gusta que no tenga un diseño demasiado llamativo.",
      "El precio debería ser competitivo porque hay muchas alternativas.",
    ],
  },
  {
    title: "Monitor 27 pulgadas para productividad",
    content: "Un monitor amplio con buena resolución para trabajar con varias ventanas, editar contenido y mejorar la comodidad visual.",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    likes: 2870,
    shares: 211,
    impressions: 46800,
    comments: [
      "Un monitor de 27 pulgadas cambia totalmente la forma de trabajar.",
      "Me interesa si tiene buena calidad de color.",
      "Para programar viene genial tener más espacio en pantalla.",
      "¿Tiene soporte regulable en altura?",
      "La productividad mejora mucho cuando puedes tener varias ventanas abiertas.",
      "Me gustaría saber si sirve para gaming también.",
      "El diseño de los bordes se ve bastante limpio.",
      "Si tiene USB-C sería perfecto.",
      "Parece buena opción para home office.",
      "El precio decidirá si compensa frente a otras marcas.",
    ],
  },
  {
    title: "Silla ergonómica para oficina y estudio",
    content: "Una silla diseñada para mantener una postura cómoda durante largas jornadas, con soporte lumbar y ajustes personalizables.",
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8",
    likes: 2240,
    shares: 130,
    impressions: 33700,
    comments: [
      "Invertir en una buena silla es de las mejores decisiones si trabajas desde casa.",
      "Me interesa mucho el soporte lumbar.",
      "La mayoría de sillas baratas acaban siendo incómodas después de un mes.",
      "¿El reposabrazos es ajustable?",
      "Se ve bastante cómoda para estudiar varias horas.",
      "El diseño es profesional, no parece una silla gaming exagerada.",
      "Me gustaría saber si el material da calor en verano.",
      "Si aguanta bien el uso diario, merece la pena.",
      "Buena opción para programadores.",
      "El montaje debería ser sencillo.",
    ],
  },
  {
    title: "Cámara web Full HD para videollamadas",
    content: "Una cámara compacta con buena calidad de imagen y micrófono integrado para reuniones, clases online y creación de contenido.",
    image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
    likes: 890,
    shares: 47,
    impressions: 12400,
    comments: [
      "La calidad de la cámara del portátil suele ser horrible, esto hace falta.",
      "Me interesa si funciona bien con poca luz.",
      "Para reuniones de trabajo puede mejorar mucho la imagen profesional.",
      "¿El micrófono integrado cancela ruido?",
      "Se ve pequeña y fácil de colocar.",
      "Buena opción para clases online.",
      "Me gustaría que incluyera tapa de privacidad.",
      "Si es plug and play, mucho mejor.",
      "La compraría para entrevistas online.",
      "El precio tiene que ser razonable porque hay muchas webcams similares.",
    ],
  },
  {
    title: "Base refrigeradora para portátil",
    content: "Mantén tu portátil más fresco durante sesiones intensas de trabajo, edición o gaming con una base ventilada y ajustable.",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853",
    likes: 760,
    shares: 39,
    impressions: 10200,
    comments: [
      "Mi portátil se calienta muchísimo cuando uso varias apps.",
      "Esto puede venir bien para programar durante horas.",
      "Me gustaría saber si los ventiladores hacen mucho ruido.",
      "La inclinación también ayuda bastante a escribir mejor.",
      "Buena idea para portátiles gaming.",
      "Si realmente baja la temperatura, merece la pena.",
      "El diseño parece sencillo pero funcional.",
      "¿Sirve para portátiles de 15,6 pulgadas?",
      "Me preocupa que ocupe demasiado en la mesa.",
      "Interesante para alargar la vida del portátil.",
    ],
  },
  {
    title: "Cargador rápido USB-C de 100W",
    content: "Carga portátil, móvil, tablet y otros dispositivos con un cargador compacto de alta potencia compatible con USB-C Power Delivery.",
    image: "https://images.unsplash.com/photo-1615526675159-e248c3021d3f",
    likes: 1190,
    shares: 78,
    impressions: 17600,
    comments: [
      "Un cargador único para todo sería comodísimo.",
      "Me interesa si puede cargar un portátil mientras uso el ordenador.",
      "El tamaño compacto es importante para viajar.",
      "¿Incluye cable USB-C de buena calidad?",
      "100W está muy bien para portátiles modernos.",
      "Me gustaría saber si se calienta mucho.",
      "Perfecto para llevar en la mochila.",
      "Si tiene varios puertos, mejor todavía.",
      "Esto evita tener mil cargadores por casa.",
      "Buena compra para estudiantes y trabajadores remotos.",
    ],
  },
  {
    title: "Soporte ajustable para portátil",
    content: "Eleva la pantalla de tu portátil y mejora tu postura con un soporte estable, plegable y fácil de transportar.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
    likes: 1330,
    shares: 91,
    impressions: 20300,
    comments: [
      "Desde que uso soporte para portátil me duele menos el cuello.",
      "Parece útil para estudiar en bibliotecas o cafeterías.",
      "Me gusta que sea plegable.",
      "¿Es estable con portátiles grandes?",
      "Muy buena opción para mejorar postura sin gastar mucho.",
      "Combinado con teclado externo queda perfecto.",
      "El diseño se ve bastante limpio.",
      "Me gustaría saber el peso.",
      "Ideal para setups pequeños.",
      "Esto debería ser básico para cualquiera que use portátil a diario.",
    ],
  },
  {
    title: "Altavoz Bluetooth compacto para casa",
    content: "Un altavoz pequeño con sonido potente, buena autonomía y conexión rápida para escuchar música en cualquier habitación.",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1",
    likes: 1740,
    shares: 102,
    impressions: 26400,
    comments: [
      "Me gusta que sea compacto, no quiero algo enorme en el escritorio.",
      "La autonomía es clave en este tipo de productos.",
      "¿Tiene buenos bajos?",
      "Se ve ideal para una habitación pequeña.",
      "El diseño es bastante elegante.",
      "Me interesa si se puede conectar con dos dispositivos.",
      "Buena opción para escuchar música mientras trabajas.",
      "Si resiste salpicaduras, mejor para llevarlo fuera.",
      "El sonido debería ser claro, no solo fuerte.",
      "Parece una buena idea para regalar.",
    ],
  },
  {
    title: "Power bank de alta capacidad para trabajar fuera",
    content: "Una batería externa potente para cargar móvil, tablet o portátil cuando estudias, viajas o trabajas lejos de un enchufe.",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5",
    likes: 2480,
    shares: 167,
    impressions: 42100,
    comments: [
      "Esto es justo lo que necesito para trabajar desde cafeterías.",
      "Me interesa si puede cargar portátiles por USB-C.",
      "La capacidad parece buena, pero el peso también importa.",
      "Ideal para viajes largos.",
      "¿Permiten llevarlo en avión?",
      "Me gustaría ver cuántas cargas completas da a un móvil.",
      "Si tiene carga rápida, es muy útil.",
      "Buena opción para estudiantes que pasan todo el día fuera.",
      "El diseño se ve robusto.",
      "La pantalla con porcentaje sería un punto extra.",
    ],
  },
  {
    title: "Tablet ligera para estudiar y tomar notas",
    content: "Una tablet pensada para leer, organizar apuntes, ver clases online y trabajar de forma cómoda desde cualquier lugar.",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0",
    likes: 3020,
    shares: 196,
    impressions: 48900,
    comments: [
      "Para tomar apuntes puede ser mucho más cómodo que llevar libretas.",
      "Me interesa si funciona bien con lápiz táctil.",
      "La usaría para ver clases y leer PDFs.",
      "El peso es importante si la llevas todos los días.",
      "¿Tiene buena autonomía?",
      "Me gusta para estudiar fuera de casa.",
      "Si el precio es competitivo, puede ser muy buena compra.",
      "La pantalla debería verse bien en exteriores.",
      "Ideal para estudiantes.",
      "Me gustaría saber si permite multitarea fluida.",
    ],
  },
  {
    title: "Hub USB-C con múltiples conexiones",
    content: "Convierte un solo puerto USB-C en HDMI, USB, lector de tarjetas y carga rápida para trabajar con más comodidad.",
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761",
    likes: 980,
    shares: 66,
    impressions: 15100,
    comments: [
      "Los portátiles modernos traen poquísimos puertos, esto es necesario.",
      "Me interesa si el HDMI soporta 4K.",
      "Perfecto para conectar monitor, teclado y ratón.",
      "¿Se calienta mucho al usarlo varias horas?",
      "Muy útil para trabajar en escritorio con portátil.",
      "Me gustaría que tuviera lector SD.",
      "Si permite cargar mientras conectas periféricos, genial.",
      "El tamaño parece fácil de transportar.",
      "Buena compra para productividad.",
      "Hay hubs baratos que fallan rápido, espero que este sea resistente.",
    ],
  },
  {
    title: "Micrófono USB para streaming y reuniones",
    content: "Mejora tu calidad de audio en videollamadas, podcasts o directos con un micrófono USB fácil de configurar.",
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc",
    likes: 1460,
    shares: 88,
    impressions: 21700,
    comments: [
      "El audio suele importar más que la cámara en reuniones.",
      "Me interesa para grabar vídeos cortos.",
      "¿Incluye soporte o brazo?",
      "Si reduce ruido de fondo, puede ser muy buena opción.",
      "El diseño se ve bastante profesional.",
      "Me gustaría saber si es plug and play.",
      "Perfecto para podcasts básicos.",
      "Para clases online también viene bien.",
      "El precio parece importante porque hay mucha competencia.",
      "Buena mejora frente al micrófono del portátil.",
    ],
  },
  {
    title: "Organizador de cables para escritorio",
    content: "Mantén tu zona de trabajo limpia y ordenada con accesorios simples para ocultar cables y mejorar la estética del setup.",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2",
    likes: 690,
    shares: 53,
    impressions: 9800,
    comments: [
      "Necesito esto urgentemente, mi escritorio está lleno de cables.",
      "Parece una solución simple pero muy útil.",
      "El setup cambia mucho cuando los cables no se ven.",
      "Me gustaría que incluyera clips adhesivos.",
      "Ideal para escritorios pequeños.",
      "No es un producto emocionante, pero sí necesario.",
      "La estética mejora muchísimo.",
      "¿Sirve para cables gruesos de monitor?",
      "Buena compra si trabajas desde casa.",
      "Me gusta porque ayuda a tener todo más limpio visualmente.",
    ],
  },
  {
    title: "Disco SSD externo para copias de seguridad",
    content: "Guarda proyectos, fotos y documentos importantes en un SSD externo rápido, resistente y fácil de transportar.",
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b",
    likes: 1870,
    shares: 119,
    impressions: 29500,
    comments: [
      "Hacer copias de seguridad debería ser obligatorio.",
      "Me interesa la velocidad de transferencia.",
      "Perfecto para guardar proyectos grandes.",
      "¿Es compatible con Mac y Windows?",
      "El tamaño compacto es muy cómodo.",
      "Un SSD externo da mucha más tranquilidad.",
      "Me gustaría saber si resiste golpes.",
      "Ideal para creadores de contenido.",
      "El precio por capacidad será lo más importante.",
      "Muy útil para estudiantes de programación o diseño.",
    ],
  },
  {
    title: "Kit de limpieza para dispositivos electrónicos",
    content: "Limpia pantallas, teclados, auriculares y accesorios con un kit seguro y práctico para mantener tus dispositivos como nuevos.",
    image: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a",
    likes: 540,
    shares: 34,
    impressions: 7600,
    comments: [
      "Mi teclado necesita esto desde hace meses.",
      "Es un producto simple pero bastante útil.",
      "Me interesa si sirve para limpiar pantallas sin dañarlas.",
      "Los auriculares acumulan mucha suciedad, viene bien.",
      "Buena idea para mantener el setup cuidado.",
      "¿Incluye líquido limpiador?",
      "Me gusta que sea compacto.",
      "Perfecto para llevar en la mochila.",
      "No parece imprescindible, pero cuando lo tienes lo usas mucho.",
      "Buen producto para añadir a una compra más grande.",
    ],
  },
  {
    title: "Mesa elevable para trabajar sentado o de pie",
    content: "Una mesa regulable en altura para alternar entre trabajar sentado y de pie, mejorando comodidad y movimiento durante el día.",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72",
    likes: 2750,
    shares: 173,
    impressions: 44700,
    comments: [
      "Trabajar de pie algunas horas cambia mucho la energía del día.",
      "Me interesa si el motor hace mucho ruido.",
      "El precio suele ser alto, pero puede merecer la pena.",
      "Ideal para gente que trabaja desde casa.",
      "Me gustaría saber cuánto peso soporta.",
      "El diseño se ve muy limpio.",
      "Alternar posturas ayuda bastante con la espalda.",
      "Necesitaría una versión para espacios pequeños.",
      "Si es estable al subirla, muy buena opción.",
      "Producto premium, pero muy útil a largo plazo.",
    ],
  },
  {
    title: "Cámara instantánea para recuerdos físicos",
    content: "Captura momentos especiales y obtén fotos impresas al instante con una cámara compacta, divertida y fácil de usar.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32",
    likes: 2130,
    shares: 158,
    impressions: 31900,
    comments: [
      "Me encanta la idea de tener fotos físicas otra vez.",
      "Es perfecta para viajes y fiestas.",
      "El coste del papel suele ser lo peor de estas cámaras.",
      "El diseño tiene un toque retro muy bonito.",
      "Buena opción para regalar.",
      "Me gustaría saber si las fotos salen con buena calidad.",
      "No es algo necesario, pero sí divertido.",
      "Ideal para crear álbumes reales.",
      "Me gusta para eventos familiares.",
      "Si el pack incluye papel, mejor todavía.",
    ],
  },
  {
    title: "Mini proyector portátil para cine en casa",
    content: "Disfruta películas, series o presentaciones en gran formato con un proyector compacto fácil de mover y configurar.",
    image: "https://images.unsplash.com/photo-1601944179066-29786cb9d32a",
    likes: 2390,
    shares: 181,
    impressions: 37600,
    comments: [
      "Me gustaría usarlo para ver películas en la habitación.",
      "La calidad de imagen con luz ambiente es lo que más me preocupa.",
      "Si es fácil de conectar al móvil, puede ser muy cómodo.",
      "Ideal para noches de cine en casa.",
      "El sonido integrado normalmente no suele ser muy bueno.",
      "Me interesa si tiene buena resolución real.",
      "Parece fácil de transportar.",
      "Buen producto para estudiantes que viven en pisos pequeños.",
      "El precio puede hacerlo muy atractivo.",
      "Me gustaría ver una demo proyectando en pared blanca.",
    ],
  },
  {
    title: "Botella térmica reutilizable para el día a día",
    content: "Mantén tus bebidas frías o calientes durante horas con una botella resistente, reutilizable y fácil de llevar.",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8",
    likes: 1120,
    shares: 71,
    impressions: 16800,
    comments: [
      "Uso botella térmica todos los días y es súper práctica.",
      "Me interesa si mantiene el agua fría muchas horas.",
      "El diseño se ve bastante elegante.",
      "Buena alternativa a comprar botellas de plástico.",
      "¿Cabe en el portavasos del coche?",
      "Perfecta para clase, gimnasio o trabajo.",
      "Me gustaría que no cogiera olor con el tiempo.",
      "Si no pierde agua en la mochila, genial.",
      "Producto simple pero muy útil.",
      "El tamaño parece cómodo para llevarlo encima.",
    ],
  },
  {
    title: "Pack de libretas premium para organización",
    content: "Organiza ideas, tareas y proyectos con libretas de diseño limpio, papel de calidad y formato cómodo para el día a día.",
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db",
    likes: 830,
    shares: 44,
    impressions: 11600,
    comments: [
      "Aunque uso apps, escribir en papel me ayuda a organizarme mejor.",
      "El diseño minimalista me gusta mucho.",
      "Me interesa saber si el papel traspasa con rotuladores.",
      "Buen producto para estudiantes.",
      "La calidad del papel marca mucha diferencia.",
      "Me gustaría que hubiera varios tamaños.",
      "Ideal para planificar proyectos.",
      "No es algo tecnológico, pero encaja muy bien con productividad.",
      "Si incluye páginas punteadas, mejor.",
      "Me parece buena opción para regalar.",
    ],
  },
]